spring:
  profiles:
    active:
      - manual
  application:
    name: 331-backend
  datasource:
    url:
      jdbc:mysql://localhost:3306/selabdb?createDatabaseIfNotExist=true&autoReconnect=true&c
      haracterEncoding=UTF-8&allowMultiQueries=true&allow PublicKeyRetrieval=true&useSSL=fals
      e&useUnicode=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create